### ISSUE TITLE
No longer working in latest build

### ISSUE THREAD

**Issue by kevinchappell** [Floobits/floobits-sublime#237]
Upgraded Sublime Text to 3126 and found Floobits no longer works, like at all. Typing "floobits" in command palette shows nothing, and all menu items are disabled out.

After testing several versions I found this behavior starts in Sublime Text 3121, builds 3120 and earlier have no issue.

Video:
[![screenshot from 2016-10-08 14-25-53](https://cloud.githubusercontent.com/assets/1457540/19213376/28146a6c-8d63-11e6-8373-6eb86ba0a317.png)](https://www.youtube.com/watch?v=QxrMHv-3L38)

*Edit:*
Forgot to include platform info.
OS: Ubuntu 16.04 x64
Kernel: 4.4.0-38-generic
Sublime Text Version: 3126

Console output:
```
...
reloading plugin Babel.Babel
reloading plugin Emmet Style Reflector.emmet_style_reflector
reloading plugin Floobits.floobits
Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 32, in <module>
    from urllib import parse
ImportError: cannot import name parse

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 2, in <module>
    from . import dmp_monkey
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/dmp_monkey.py", line 1, in <module>
    from .diff_match_patch import diff_match_patch as dmp
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 46, in <module>
    import __builtin__
ImportError: No module named '__builtin__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 22, in <module>
    from .lib import DMP
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 4, in <module>
    import dmp_monkey
ImportError: No module named 'dmp_monkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/listener.py", line 9, in <module>
    from .common import msg, shared as G, utils
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 25, in <module>
    import editor
ImportError: No module named 'editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floobits.py", line 37, in <module>
    from .floo.listener import Listener
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/listener.py", line 13, in <module>
    from common import msg, shared as G, utils
ImportError: No module named 'common'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floobits.py", line 42, in <module>
    from floo import version
ImportError: No module named 'floo'
reloading plugin Floobits.tag_release
reloading plugin Floobits.text_commands
Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 32, in <module>
    from urllib import parse
ImportError: cannot import name parse

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 2, in <module>
    from . import dmp_monkey
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/dmp_monkey.py", line 1, in <module>
    from .diff_match_patch import diff_match_patch as dmp
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 46, in <module>
    import __builtin__
ImportError: No module named '__builtin__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 22, in <module>
    from .lib import DMP
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 4, in <module>
    import dmp_monkey
ImportError: No module named 'dmp_monkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_utils.py", line 4, in <module>
    from .common import msg, shared as G, utils
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 25, in <module>
    import editor
ImportError: No module named 'editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/text_commands.py", line 8, in <module>
    from .floo import sublime_utils as sutils
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_utils.py", line 7, in <module>
    from common import msg, shared as G, utils
ImportError: No module named 'common'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/text_commands.py", line 12, in <module>
    from floo import sublime_utils as sutils
ImportError: No module named 'floo'
reloading plugin Floobits.window_commands
Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 32, in <module>
    from urllib import parse
ImportError: cannot import name parse

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 2, in <module>
    from . import dmp_monkey
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/dmp_monkey.py", line 1, in <module>
    from .diff_match_patch import diff_match_patch as dmp
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/diff_match_patch.py", line 46, in <module>
    import __builtin__
ImportError: No module named '__builtin__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 22, in <module>
    from .lib import DMP
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/lib/__init__.py", line 4, in <module>
    import dmp_monkey
ImportError: No module named 'dmp_monkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_connection.py", line 13, in <module>
    from .common import msg, shared as G, utils
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/common/utils.py", line 25, in <module>
    import editor
ImportError: No module named 'editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_ui.py", line 8, in <module>
    from .sublime_connection import SublimeConnection
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_connection.py", line 20, in <module>
    from floo import editor
ImportError: No module named 'floo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/window_commands.py", line 14, in <module>
    from .floo import sublime_ui
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/floo/sublime_ui.py", line 13, in <module>
    from sublime_connection import SublimeConnection
ImportError: No module named 'sublime_connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/kevin.chappell/.config/sublime-text-3/Packages/Floobits/window_commands.py", line 19, in <module>
    from floo import sublime_ui
ImportError: No module named 'floo'
```

**Comment by ggreer** [comment]
I have a laptop with Ubuntu 16.04 and am running Sublime Text 3 build 3126. I can't reproduce this.

How did you install the Floobits plugin.

**Comment by kevinchappell** [comment]
That is encouraging to know. I made another video to demonstrate the different install methods i used for ST and Floobits plugin, sorry about all the "uhs" and "ums"- im not very good at talking while thinking or typing.

Video:
[![screenshot from 2016-10-08 23-21-59](https://cloud.githubusercontent.com/assets/1457540/19216308/0a499bba-8dae-11e6-874f-30bc2309e908.png)](https://www.youtube.com/watch?v=EDK83LnCFfg)
At the end of the video I get Floobits working but only in ST 3119 and there have been many improvements in the recent versions I like so would prefer to use latest version.


Also if I haven't mentioned it yet- I'm a huge fan of Floobits and regularly extol it's benefits to remote teams. Thanks for a great product.

**Comment by kevinchappell** [comment]
After some further looking into this I found the problem cannot be Floobits. It seems another package is importing a different `urllib`.
Clean Install
![screenshot from 2016-10-09 01-48-42](https://cloud.githubusercontent.com/assets/1457540/19216898/28b7aa88-8dc7-11e6-8517-611158ba3317.png)

My Install
![screenshot from 2016-10-09 01-59-58](https://cloud.githubusercontent.com/assets/1457540/19216899/32e9cc48-8dc7-11e6-9aca-f930eb323dad.png)

You'll notice `__path__`, `error` and `parse` are missing form my install. Even after removing nearly all packages the problem persisted so i deleted `~/.config/sublime-text-3` and started over. Will report back if I ever find what caused this to happen.

**Comment by ggreer** [comment]
Thank you for troubleshooting this. If another package is the culprit, please let me know.

**Comment by Pedro-vk** [comment]
Not solution for that?

**Comment by kevinchappell** [comment]
@Pedro-vk I never figured out what package caused the problem but after clearing config and reinstalling packages started working again.
